rabbitmq: 
  host: localhost 
  port: 5672
  user: guest
  password: guest
  queues:
    - lazypersistence
    - transmissoes

mongodb: 
  host: localhost 
  port: 27017
  database: test

maxmessages: 30
retentionseconds: 30
logfile: /home/rodrigo/lazypersistence.log