rabbitmq: 
  host: localhost 
  port: 5672
  user: guest
  password: guest
  queues:
    - queue: 
      name: lazypersistence
      exchange: monitriip 
      exchangetype: topic 
      routingkey: monitriip.transmissoes
      dlqexchange: lazypersistence.DLQ
      dlqexchangetype: direct 
      dlqroutingkey: erros
      durable: true 
    - queue: 
      name: transmissoes
      durable: true

mongodb: 
  host: localhost 
  port: 27017
  database: test

maxmessages: 30
retentionseconds: 30
logfile: /home/rodrigo/lazypersistence.log